import type { Locale } from './index'

export type ArticleSection = {
  heading: string
  paragraphs: string[]
  subsections?: { heading: string; paragraphs: string[] }[]
}

export type Article = {
  slug: string
  alternateSlug: string
  title: string
  seoTitle: string
  description: string
  category: string
  date: string
  intro: string[]
  sections: ArticleSection[]
  relatedServices: string[]
  relatedArticles: string[]
}

const ptArticles: Article[] = [
  {
    slug: 'o-que-e-gestao-de-redes-sociais', alternateSlug: 'what-is-social-media-management',
    title: 'O que é gestão de redes sociais e o que uma empresa realmente recebe?', seoTitle: 'O que é Gestão de Redes Sociais para Empresas?',
    description: 'Entenda o que faz parte de uma gestão profissional de redes sociais, como funciona o processo e o que avaliar antes de contratar.', category: 'Redes sociais', date: '2026-08-19',
    intro: ['Gestão de redes sociais não é apenas criar posts. Para uma empresa, o serviço organiza estratégia, repertório, produção e rotina para que cada canal cumpra um papel claro na construção da marca.', 'O escopo muda conforme o negócio, mas uma operação profissional precisa explicar como decisões são tomadas, quem participa e o que será entregue.'],
    sections: [
      { heading: 'O que é gestão de redes sociais?', paragraphs: ['É a coordenação contínua da presença da empresa em canais como Instagram e LinkedIn. O trabalho parte dos objetivos e do posicionamento para definir temas, linguagem, formatos, calendário e critérios de acompanhamento.', 'Isso evita que a comunicação dependa de tendências aleatórias ou da urgência de publicar. Conteúdo passa a ser uma expressão organizada da marca.'] },
      { heading: 'O que a empresa pode receber', paragraphs: ['Um escopo pode reunir diagnóstico, estratégia editorial, planejamento de pautas, redação, direção criativa, design, produção, organização de aprovações e acompanhamento. Gestão de comunidade, mídia paga ou captação audiovisual devem ser explicitadas quando fizerem parte.', 'O ponto central não é a quantidade isolada de posts, mas a relação entre objetivo, qualidade, frequência e capacidade operacional.'] },
      { heading: 'Como funciona o processo', paragraphs: ['Primeiro vem a imersão no negócio, no público e na marca. Depois são definidos pilares editoriais, formatos e fluxo de produção. O calendário transforma essa direção em entregas, enquanto revisões periódicas ajudam a evoluir a pauta sem abandonar a coerência.', 'A empresa também participa: disponibiliza conhecimento, valida informações e mantém decisões comerciais atualizadas. Uma boa gestão não funciona como uma caixa-preta.'] },
      { heading: 'Como escolher um parceiro', paragraphs: ['Procure clareza sobre estratégia, responsabilidades, aprovação e critérios de qualidade. Observe se o parceiro entende marca e negócio ou oferece somente um pacote indiferenciado.', 'A Studio Cora integra branding, direção criativa e execução para empresas que precisam de uma presença editorial consistente e própria.'] },
    ], relatedServices: ['gestao-de-redes-sociais', 'branding'], relatedArticles: ['quanto-custa-gestao-de-redes-sociais', 'como-saber-se-empresa-precisa-social-media'],
  },
  {
    slug: 'quanto-custa-gestao-de-redes-sociais', alternateSlug: 'social-media-management-cost',
    title: 'Quanto custa gestão de redes sociais para empresas?', seoTitle: 'Preço da Gestão de Redes Sociais para Empresas',
    description: 'Veja quais fatores formam o preço da gestão de redes sociais e como comparar propostas além da quantidade de posts.', category: 'Redes sociais', date: '2026-08-19',
    intro: ['Não existe um preço único para gestão de redes sociais porque “gerenciar” pode representar escopos muito diferentes. Uma proposta pode cobrir apenas planejamento e design; outra pode incluir estratégia, redação, vídeo, publicação e acompanhamento.', 'Antes de comparar valores, é preciso tornar as responsabilidades comparáveis.'],
    sections: [
      { heading: 'O que influencia o investimento', paragraphs: ['Número de canais, frequência, variedade de formatos, profundidade estratégica, volume de aprovações e necessidade de captação alteram o esforço. A maturidade da marca também importa: quando posicionamento e identidade não estão definidos, a operação exige uma base adicional.', 'Prazos curtos e muitos interlocutores aumentam complexidade mesmo quando o número de peças parece pequeno.'] },
      { heading: 'Por que preço por post é insuficiente', paragraphs: ['O post é apenas a parte visível. Pesquisa, pauta, texto, direção, design, revisão e coordenação acontecem antes da publicação. Comparar somente preço unitário pode esconder diferenças importantes de senioridade e processo.', 'Uma proposta útil separa entregáveis, premissas e itens fora do escopo. Assim a empresa entende o que está financiando.'] },
      { heading: 'Como avaliar uma proposta', paragraphs: ['Verifique quem define a estratégia, quais formatos estão incluídos, como funcionam aprovação e alterações e o que a empresa precisa fornecer. Pergunte também como o trabalho se conecta ao posicionamento da marca.', 'O melhor escopo não é necessariamente o maior. É o que a equipe consegue sustentar com qualidade e informação.'] },
      { heading: 'Como pedir um orçamento mais preciso', paragraphs: ['Compartilhe objetivos, canais atuais, frequência desejada, equipe disponível e gargalos. Informar se já existem estratégia de marca, identidade e acervo reduz suposições.', 'Na Studio Cora, o escopo é construído a partir da realidade da empresa, sem prometer desempenho comercial que conteúdo sozinho não controla.'] },
    ], relatedServices: ['gestao-de-redes-sociais'], relatedArticles: ['o-que-e-gestao-de-redes-sociais', 'como-saber-se-empresa-precisa-social-media'],
  },
  {
    slug: 'branding-e-identidade-visual-diferenca', alternateSlug: 'branding-vs-visual-identity',
    title: 'Branding e identidade visual: qual é a diferença?', seoTitle: 'Branding x Identidade Visual: Entenda a Diferença',
    description: 'Entenda o papel do branding, da identidade visual e quando uma empresa precisa trabalhar as duas frentes.', category: 'Branding', date: '2026-08-19',
    intro: ['Branding e identidade visual estão ligados, mas resolvem partes diferentes da construção de uma marca. Confundir os dois leva empresas a esperar que um novo logotipo resolva um problema de posicionamento.', 'A diferença fica mais clara quando observamos as decisões que cada frente organiza.'],
    sections: [
      { heading: 'O que branding organiza', paragraphs: ['Branding define como a empresa quer ser compreendida: posicionamento, proposta de valor, atributos, narrativa e princípios de experiência. Ele cria critérios para decisões de comunicação, produto e relacionamento.', 'Não se limita ao que a marca parece. Trata da coerência entre o que ela promete, entrega e expressa.'] },
      { heading: 'O que a identidade visual organiza', paragraphs: ['Identidade visual transforma a estratégia em um sistema reconhecível. Pode incluir logotipo, tipografia, cores, composição, grafismos, imagens e regras de aplicação.', 'Seu valor está na capacidade de manter unidade sem tornar todas as peças iguais.'] },
      { heading: 'Quando trabalhar as duas frentes', paragraphs: ['Se a empresa não consegue explicar sua diferença, mudar apenas o visual tende a maquiar a questão. Se o posicionamento está claro, mas a expressão é inconsistente ou ultrapassada, a identidade pode ser o foco principal.', 'Em muitos projetos, a etapa estratégica vem primeiro e orienta o sistema visual.'] },
      { heading: 'Uma pergunta prática', paragraphs: ['Se o problema é “não sabemos o que dizer e por que escolher nossa marca”, comece por branding. Se é “sabemos quem somos, mas não conseguimos parecer consistentes”, investigue a identidade visual.', 'Um diagnóstico evita comprar a solução errada para o problema certo.'] },
    ], relatedServices: ['branding', 'identidade-visual'], relatedArticles: ['quando-empresa-precisa-rebranding', 'branding-antes-de-trafego-pago'],
  },
  {
    slug: 'quando-empresa-precisa-rebranding', alternateSlug: 'when-does-a-company-need-rebranding',
    title: 'Quando uma empresa precisa de rebranding?', seoTitle: 'Quando uma Empresa Precisa de Rebranding?',
    description: 'Conheça sinais de que a marca precisa ser revista e entenda quando evolução é melhor do que uma ruptura completa.', category: 'Branding', date: '2026-08-19',
    intro: ['Rebranding não deve começar pelo desejo de “modernizar o logo”. Ele faz sentido quando existe uma distância relevante entre o negócio atual e a forma como a marca é percebida ou operada.', 'A mudança pode ser profunda ou evolutiva. O diagnóstico define o tamanho correto.'],
    sections: [
      { heading: 'Sinais estratégicos', paragraphs: ['A empresa mudou de mercado, ampliou a oferta, passou a atender outro perfil de cliente ou enfrenta dificuldade para explicar sua diferença. Também pode haver conflito entre áreas sobre mensagens e prioridades.', 'Esses sinais apontam para posicionamento e arquitetura de marca, não apenas para estética.'] },
      { heading: 'Sinais visuais e operacionais', paragraphs: ['A identidade não funciona bem em ambientes digitais, cada equipe cria materiais de um jeito ou o sistema depende de exceções constantes. Inconsistência aumenta retrabalho e enfraquece reconhecimento.', 'Ainda assim, elementos conhecidos não devem ser descartados automaticamente. Reconhecimento existente é um ativo a avaliar.'] },
      { heading: 'Evolução ou mudança completa?', paragraphs: ['Uma evolução preserva códigos úteis e corrige o que perdeu função. Uma transformação maior é indicada quando estratégia, nome, público ou proposta mudaram de forma substancial.', 'A decisão deve considerar risco, capacidade de implementação e pontos de contato que precisarão ser atualizados.'] },
      { heading: 'Como preparar o projeto', paragraphs: ['Reúna percepções de clientes e equipe, materiais atuais, objetivos de negócio e limitações de aplicação. Defina quem decide e quem implementará a nova marca.', 'Rebranding termina na adoção, não na apresentação do conceito.'] },
    ], relatedServices: ['branding', 'identidade-visual'], relatedArticles: ['branding-e-identidade-visual-diferenca'],
  },
  {
    slug: 'landing-page-ou-site-institucional', alternateSlug: 'landing-page-vs-corporate-website',
    title: 'Landing page ou site institucional: qual escolher?', seoTitle: 'Landing Page ou Site: Qual Escolher?',
    description: 'Compare objetivos, estrutura e uso de landing pages e sites institucionais para escolher o formato certo.', category: 'Web', date: '2026-08-19',
    intro: ['Landing page e site institucional não são versões pequena e grande da mesma coisa. Eles organizam jornadas diferentes.', 'A escolha correta depende da pergunta que o visitante precisa responder e da ação que a empresa espera.'],
    sections: [
      { heading: 'Quando uma landing page faz sentido', paragraphs: ['Ela é adequada quando existe uma oferta, um público e uma ação principal: solicitar contato, inscrever-se, baixar um material ou avançar em uma campanha. A narrativa é concentrada e reduz caminhos paralelos.', 'Isso não significa uma página curta. Significa foco.'] },
      { heading: 'Quando o site institucional é necessário', paragraphs: ['O site atende pessoas com intenções variadas: entender a empresa, comparar serviços, conhecer projetos, buscar conteúdo ou entrar em contato. Ele cria uma base permanente para marca e SEO.', 'Empresas com várias ofertas ou ciclo de decisão mais longo geralmente precisam dessa amplitude.'] },
      { heading: 'Os dois podem trabalhar juntos', paragraphs: ['O site sustenta autoridade e descoberta contínua. Landing pages podem atender campanhas específicas sem obrigar toda pessoa a navegar pela arquitetura completa.', 'Manter identidade, analytics e mensagens coerentes entre os dois evita uma experiência fragmentada.'] },
      { heading: 'Critérios para decidir', paragraphs: ['Defina objetivo, origem do tráfego, quantidade de ofertas, necessidade de SEO e manutenção futura. Se ainda há dúvida sobre posicionamento e conteúdo, resolva isso antes de escolher tecnologia.', 'A Studio Cora projeta landing pages e sites institucionais conectando mensagem, interface e desenvolvimento.'] },
    ], relatedServices: ['landing-pages', 'desenvolvimento-web'], relatedArticles: ['quanto-custa-criar-site-profissional'],
  },
  {
    slug: 'quanto-custa-criar-site-profissional', alternateSlug: 'professional-website-cost',
    title: 'Quanto custa criar um site profissional?', seoTitle: 'Quanto Custa Criar um Site Profissional?',
    description: 'Entenda os fatores que formam o custo de um site profissional e como comparar propostas de desenvolvimento.', category: 'Web', date: '2026-08-19',
    intro: ['O custo de um site profissional depende menos do número bruto de páginas do que da combinação entre estratégia, conteúdo, design, tecnologia e integrações.', 'Dois sites com cinco páginas podem exigir esforços completamente diferentes.'],
    sections: [
      { heading: 'O que compõe o projeto', paragraphs: ['Descoberta, arquitetura de informação, copy, interface, desenvolvimento, responsividade, acessibilidade, SEO técnico, integrações e publicação são frentes distintas. Nem toda proposta inclui todas elas.', 'Conteúdo desorganizado e muitas regras específicas também aumentam a complexidade.'] },
      { heading: 'Template e projeto sob medida', paragraphs: ['Templates podem atender necessidades simples e acelerar a publicação, mas impõem limites de estrutura e diferenciação. Um projeto sob medida é indicado quando marca, conteúdo, performance e evolução exigem decisões próprias.', 'A escolha deve considerar custo de manutenção, não só investimento inicial.'] },
      { heading: 'Como comparar propostas', paragraphs: ['Confirme quem cria conteúdo e design, quais páginas e estados estão previstos, como serão feitos testes e quais integrações entram no escopo. Pergunte sobre hospedagem, suporte e autonomia após a entrega.', 'Preço baixo pode esconder trabalho que ficará sob responsabilidade da empresa.'] },
      { heading: 'Como chegar a um orçamento', paragraphs: ['Prepare objetivos, públicos, referências, conteúdo disponível, funcionalidades e prazo. Um briefing honesto permite separar necessidades atuais de evoluções futuras.', 'A Studio Cora combina direção criativa e desenvolvimento para reduzir a distância entre o que foi desenhado e o que chega à produção.'] },
    ], relatedServices: ['desenvolvimento-web', 'landing-pages'], relatedArticles: ['landing-page-ou-site-institucional'],
  },
  {
    slug: 'como-saber-se-empresa-precisa-social-media', alternateSlug: 'does-your-company-need-social-media-management',
    title: 'Como saber se sua empresa precisa de um social media?', seoTitle: 'Sua Empresa Precisa de Social Media?',
    description: 'Veja os sinais de que a empresa precisa profissionalizar estratégia, produção e gestão de redes sociais.', category: 'Redes sociais', date: '2026-08-19',
    intro: ['Nem toda empresa precisa publicar todos os dias, mas toda empresa que usa redes sociais precisa decidir qual papel esses canais cumprem.', 'Um profissional ou estúdio de social media se torna necessário quando improviso começa a comprometer consistência, tempo e percepção de marca.'],
    sections: [
      { heading: 'Sinais de que a operação precisa mudar', paragraphs: ['A pauta depende sempre da última hora, o visual muda a cada publicação, ninguém sabe o que aprovar ou a liderança concentra toda a produção. Outro sinal é ter bom conhecimento interno que nunca chega ao público.', 'Esses problemas revelam falta de sistema, não falta de ideias.'] },
      { heading: 'Equipe interna ou parceiro externo?', paragraphs: ['Uma equipe interna acompanha o cotidiano de perto e pode responder com velocidade. Um parceiro externo traz método, repertório e capacidade especializada. Muitas operações funcionam melhor de forma híbrida.', 'A decisão depende de volume, complexidade, disponibilidade de especialistas e capacidade de gestão.'] },
      { heading: 'O que organizar antes de contratar', paragraphs: ['Defina objetivos, responsáveis, canais prioritários e quem fornecerá conhecimento técnico. Reúna identidade, ofertas, calendário comercial e restrições.', 'Quanto mais claro o acesso à informação, melhor o conteúdo representa a empresa.'] },
      { heading: 'O que esperar do trabalho', paragraphs: ['Espere direção editorial, processo, consistência e melhoria gradual. Não espere que redes sociais corrijam sozinhas uma oferta confusa ou garantam vendas.', 'A Studio Cora é indicada para empresas que valorizam estratégia de marca e qualidade de execução no mesmo processo.'] },
    ], relatedServices: ['gestao-de-redes-sociais'], relatedArticles: ['o-que-e-gestao-de-redes-sociais', 'quanto-custa-gestao-de-redes-sociais'],
  },
  {
    slug: 'branding-antes-de-trafego-pago', alternateSlug: 'branding-before-paid-media',
    title: 'Por que investir em branding antes de tráfego pago?', seoTitle: 'Branding Antes de Investir em Tráfego Pago',
    description: 'Entenda como posicionamento, mensagem e identidade influenciam a experiência criada depois do clique em um anúncio.', category: 'Branding', date: '2026-08-19',
    intro: ['Tráfego pago compra atenção; não cria automaticamente uma marca clara ou uma oferta convincente. Quando posicionamento, mensagem e experiência estão desalinhados, aumentar alcance também amplia a exposição dessas fragilidades.', 'Branding não substitui mídia. Ele prepara uma base mais coerente para aproveitá-la.'],
    sections: [
      { heading: 'O que acontece depois do clique', paragraphs: ['A pessoa compara promessa do anúncio, página, identidade, oferta e sinais de confiança. Se cada ponto parece pertencer a uma empresa diferente, a decisão exige mais esforço.', 'Branding organiza essa continuidade e ajuda a equipe a repetir uma mensagem reconhecível.'] },
      { heading: 'O mínimo que precisa estar claro', paragraphs: ['A empresa deve saber para quem fala, qual problema resolve, por que sua abordagem é relevante e qual ação espera. Também precisa de uma identidade funcional e uma página adequada à campanha.', 'Não é necessário esperar uma marca “perfeita”, mas contradições centrais devem ser resolvidas.'] },
      { heading: 'Quando mídia e branding avançam juntos', paragraphs: ['Campanhas podem revelar dúvidas e respostas do mercado, enquanto a estratégia de marca orienta mensagens e experiência. O aprendizado é útil quando há critérios para interpretá-lo.', 'Sem esses critérios, cada anúncio vira uma nova tentativa desconectada.'] },
      { heading: 'Uma ordem mais sustentável', paragraphs: ['Organize posicionamento e oferta, construa os pontos de contato essenciais, defina mensuração e então amplie distribuição. Essa sequência reduz retrabalho e melhora a qualidade do aprendizado.', 'A Studio Cora conecta branding, landing pages e presença digital para manter coerência entre promessa e experiência.'] },
    ], relatedServices: ['branding', 'landing-pages'], relatedArticles: ['branding-e-identidade-visual-diferenca'],
  },
]

const enArticles: Article[] = [
  {
    slug: 'what-is-social-media-management', alternateSlug: 'o-que-e-gestao-de-redes-sociais', title: 'What is social media management, and what does a company actually receive?', seoTitle: 'What Is Social Media Management for Companies?', description: 'Learn what professional social media management includes, how the process works and what to review before hiring a partner.', category: 'Social media', date: '2026-08-19',
    intro: ['Social media management is more than making posts. It turns brand strategy, internal expertise and production into a consistent presence across the channels that matter.', 'Scope varies, but a professional engagement should make decisions, responsibilities and deliverables easy to understand.'],
    sections: [{ heading: 'What social media management means', paragraphs: ['It is the ongoing coordination of a company’s presence on platforms such as Instagram and LinkedIn. Business goals and positioning inform themes, voice, formats, cadence and review criteria.', 'The result is an editorial system rather than a stream of disconnected posts.'] }, { heading: 'What may be included', paragraphs: ['A scope may cover diagnosis, editorial strategy, planning, copy, creative direction, design, production, approvals and ongoing guidance. Community management, paid media and video shoots should be named when included.', 'Post volume alone says little about the strategic and production work behind it.'] }, { heading: 'How the process works', paragraphs: ['Immersion comes first, followed by content pillars, formats and a production workflow. A calendar turns direction into deliverables, while regular reviews help the work evolve.', 'The company remains part of the process by providing expertise, validating information and sharing commercial priorities.'] }, { heading: 'What to look for in a partner', paragraphs: ['Look for clarity around strategy, responsibilities, approvals and quality. Determine whether the partner understands the brand and business or simply sells an interchangeable package.', 'Studio Cora combines branding, creative direction and execution for companies that need a distinctive editorial presence.'] }],
    relatedServices: ['social-media-management', 'branding'], relatedArticles: ['social-media-management-cost', 'does-your-company-need-social-media-management'],
  },
  {
    slug: 'social-media-management-cost', alternateSlug: 'quanto-custa-gestao-de-redes-sociais', title: 'How much does social media management cost?', seoTitle: 'Social Media Management Cost for Companies', description: 'Understand what shapes social media management pricing and how to compare proposals beyond post count.', category: 'Social media', date: '2026-08-19',
    intro: ['There is no universal price because social media management can describe very different scopes. One proposal may cover planning and design; another may include strategy, writing, video, publishing and ongoing support.', 'Before comparing fees, make the responsibilities comparable.'],
    sections: [{ heading: 'What affects the investment', paragraphs: ['Channels, cadence, format variety, strategic depth, review cycles and production needs all affect effort. Brand maturity matters too: unclear positioning or identity creates foundational work.', 'Compressed timelines and complex stakeholder structures can increase scope even with fewer deliverables.'] }, { heading: 'Why price per post is incomplete', paragraphs: ['Research, planning, writing, direction, design, review and coordination happen before a post appears. A unit price can hide substantial differences in process and seniority.', 'A useful proposal separates deliverables, assumptions and exclusions.'] }, { heading: 'How to compare proposals', paragraphs: ['Review who owns strategy, which formats are included, how revisions work and what the company must provide. Ask how content connects to brand positioning.', 'The best scope is not necessarily the largest. It is the one the organization can sustain well.'] }, { heading: 'How to request a clearer estimate', paragraphs: ['Share goals, current channels, internal resources, desired cadence and bottlenecks. Existing brand strategy, identity and content libraries should be disclosed.', 'Studio Cora builds scope around the actual company rather than promising commercial outcomes content cannot control alone.'] }],
    relatedServices: ['social-media-management'], relatedArticles: ['what-is-social-media-management', 'does-your-company-need-social-media-management'],
  },
  {
    slug: 'branding-vs-visual-identity', alternateSlug: 'branding-e-identidade-visual-diferenca', title: 'Branding vs. visual identity: what is the difference?', seoTitle: 'Branding vs Visual Identity: The Difference', description: 'Understand the roles of branding and visual identity and when a company needs to work on both.', category: 'Branding', date: '2026-08-19',
    intro: ['Branding and visual identity are connected, but they solve different parts of brand building. Treating them as synonyms creates unrealistic expectations that a new logo can fix unclear positioning.', 'The distinction becomes clearer when we look at the decisions each discipline organizes.'],
    sections: [{ heading: 'What branding organizes', paragraphs: ['Branding defines how a company wants to be understood: positioning, value proposition, attributes, narrative and experience principles. It creates criteria for communication and business decisions.', 'It is about coherence between what the brand promises, delivers and expresses.'] }, { heading: 'What visual identity organizes', paragraphs: ['Visual identity turns strategy into a recognizable system: logo, typography, color, composition, graphic elements, imagery and application rules.', 'A strong system creates unity without making every touchpoint identical.'] }, { heading: 'When both are needed', paragraphs: ['If the company cannot explain its difference, changing the look alone will not resolve the issue. If positioning is clear but expression is inconsistent, visual identity may be the primary need.', 'Strategic work often comes first and gives the visual system a useful direction.'] }, { heading: 'A practical question', paragraphs: ['If the issue is “we do not know what to say or why people should choose us,” begin with branding. If it is “we know who we are but cannot show up consistently,” investigate visual identity.', 'A diagnosis prevents buying the wrong solution for the right problem.'] }],
    relatedServices: ['branding', 'visual-identity'], relatedArticles: ['when-does-a-company-need-rebranding', 'branding-before-paid-media'],
  },
  {
    slug: 'when-does-a-company-need-rebranding', alternateSlug: 'quando-empresa-precisa-rebranding', title: 'When does a company need rebranding?', seoTitle: 'When Does a Company Need Rebranding?', description: 'Learn the signs that a brand needs review and when evolution is better than a complete break.', category: 'Branding', date: '2026-08-19',
    intro: ['Rebranding should not begin with a vague wish to modernize a logo. It becomes relevant when the current business and the way the brand is perceived or operated have moved apart.', 'The right response may be an evolution or a deeper transformation. Diagnosis determines the scale.'],
    sections: [{ heading: 'Strategic signals', paragraphs: ['The company may have entered a new market, expanded its offer, shifted audience or become difficult to explain. Internal teams may also disagree on messages and priorities.', 'These are positioning issues, not merely visual ones.'] }, { heading: 'Visual and operational signals', paragraphs: ['The identity may fail in digital environments, teams may produce inconsistent materials or the system may rely on constant exceptions. That friction creates rework and weakens recognition.', 'Existing brand equity should still be assessed before familiar elements are removed.'] }, { heading: 'Evolution or full change?', paragraphs: ['An evolution preserves useful codes and improves what no longer works. A larger transformation fits substantial changes in strategy, audience, name or offer.', 'The decision should account for implementation capacity and every touchpoint that needs updating.'] }, { heading: 'How to prepare', paragraphs: ['Gather internal and customer perspectives, current materials, business objectives and application constraints. Define decision-makers and the team responsible for rollout.', 'Rebranding succeeds through adoption, not at the concept presentation.'] }],
    relatedServices: ['branding', 'visual-identity'], relatedArticles: ['branding-vs-visual-identity'],
  },
  {
    slug: 'landing-page-vs-corporate-website', alternateSlug: 'landing-page-ou-site-institucional', title: 'Landing page or corporate website: which one do you need?', seoTitle: 'Landing Page or Company Website?', description: 'Compare the purpose and structure of landing pages and corporate websites to choose the right format.', category: 'Web', date: '2026-08-19',
    intro: ['A landing page and a corporate website are not simply small and large versions of the same thing. They support different journeys.', 'The right choice depends on the question visitors need answered and the action the company expects.'],
    sections: [{ heading: 'When a landing page works', paragraphs: ['A landing page fits one offer, one audience and one primary action. Its narrative limits competing paths and supports campaigns, launches or lead generation.', 'Focus does not necessarily mean short. It means every section supports the same decision.'] }, { heading: 'When a corporate website is necessary', paragraphs: ['A website serves multiple intentions: understanding the company, comparing services, reviewing work, reading insights or making contact. It creates a lasting foundation for brand and organic discovery.', 'Companies with several offers or longer buying journeys generally need that breadth.'] }, { heading: 'How they work together', paragraphs: ['The website supports ongoing authority and discovery. Landing pages can serve specific campaigns without forcing every visitor through the full architecture.', 'Shared brand, analytics and messaging prevent a fragmented experience.'] }, { heading: 'Criteria for deciding', paragraphs: ['Define objective, traffic source, number of offers, SEO needs and future maintenance. If positioning and content remain unclear, resolve them before selecting technology.', 'Studio Cora designs both formats by connecting message, interface and development.'] }],
    relatedServices: ['landing-pages', 'web-development'], relatedArticles: ['professional-website-cost'],
  },
  {
    slug: 'professional-website-cost', alternateSlug: 'quanto-custa-criar-site-profissional', title: 'How much does a professional website cost?', seoTitle: 'What Does a Professional Website Cost?', description: 'Understand what shapes professional website costs and how to compare design and development proposals.', category: 'Web', date: '2026-08-19',
    intro: ['Professional website cost depends less on raw page count than on strategy, content, design, technology and integrations.', 'Two five-page websites can require entirely different levels of work.'],
    sections: [{ heading: 'What makes up a website project', paragraphs: ['Discovery, information architecture, copy, interface design, development, responsive behavior, accessibility, technical SEO, integrations and launch are separate disciplines. Not every proposal includes all of them.', 'Unstructured content and complex business rules also add effort.'] }, { heading: 'Template or custom project', paragraphs: ['Templates can suit straightforward needs and speed up launch, but they constrain structure and differentiation. Custom work is useful when brand, content, performance and future evolution require specific decisions.', 'Evaluate maintenance cost as well as initial investment.'] }, { heading: 'How to compare proposals', paragraphs: ['Confirm who owns content and design, which pages and states are included, how testing works and which integrations are covered. Ask about hosting, support and post-launch autonomy.', 'A lower fee may transfer significant work back to the company.'] }, { heading: 'How to get a useful estimate', paragraphs: ['Prepare objectives, audiences, references, available content, functions and timing. A candid brief helps separate immediate needs from future phases.', 'Studio Cora combines creative direction and development to reduce the gap between design intent and production.'] }],
    relatedServices: ['web-development', 'landing-pages'], relatedArticles: ['landing-page-vs-corporate-website'],
  },
  {
    slug: 'does-your-company-need-social-media-management', alternateSlug: 'como-saber-se-empresa-precisa-social-media', title: 'Does your company need social media management?', seoTitle: 'Does Your Business Need Social Media?', description: 'Review the signs that a company needs a more professional social media strategy and production process.', category: 'Social media', date: '2026-08-19',
    intro: ['Not every company needs to publish daily, but every company using social media should decide what those channels are meant to do.', 'Professional support becomes valuable when improvisation begins to affect consistency, time and brand perception.'],
    sections: [{ heading: 'Signals the operation needs to change', paragraphs: ['Topics are always chosen at the last minute, visuals shift from post to post, approvals have no owner or leadership produces everything. Valuable internal expertise may never reach the audience.', 'These are system problems, not idea shortages.'] }, { heading: 'Internal team or external partner?', paragraphs: ['An internal team stays close to daily operations. An external partner brings process, perspective and specialist capacity. Many companies benefit from a hybrid model.', 'The choice depends on volume, complexity and management capacity.'] }, { heading: 'What to organize before hiring', paragraphs: ['Define goals, decision-makers, priority channels and sources of subject-matter expertise. Gather brand assets, offers, commercial dates and restrictions.', 'Better access to information produces more credible content.'] }, { heading: 'What to expect', paragraphs: ['Expect editorial direction, a reliable process, consistency and gradual refinement. Do not expect social media alone to repair an unclear offer or guarantee sales.', 'Studio Cora works best with companies that value brand strategy and execution quality together.'] }],
    relatedServices: ['social-media-management'], relatedArticles: ['what-is-social-media-management', 'social-media-management-cost'],
  },
  {
    slug: 'branding-before-paid-media', alternateSlug: 'branding-antes-de-trafego-pago', title: 'Why invest in branding before paid media?', seoTitle: 'Why Branding Should Come Before Paid Media', description: 'See how positioning, messaging and identity shape the experience people have after clicking an ad.', category: 'Branding', date: '2026-08-19',
    intro: ['Paid media buys attention; it does not automatically create a clear brand or compelling offer. More reach can expose existing gaps when positioning, messaging and experience do not align.', 'Branding does not replace media. It creates a stronger foundation for using it.'],
    sections: [{ heading: 'What happens after the click', paragraphs: ['People compare the ad promise with the page, identity, offer and trust signals. When each touchpoint feels like a different company, the decision requires more effort.', 'Branding creates continuity and helps teams repeat a recognizable message.'] }, { heading: 'What needs to be clear first', paragraphs: ['The company should understand its audience, problem, relevance and desired action. It also needs a functional identity and a page suited to the campaign.', 'The brand does not have to be perfect, but central contradictions should be resolved.'] }, { heading: 'When branding and media work together', paragraphs: ['Campaigns reveal market questions and responses, while brand strategy guides messages and experience. That learning is more useful when the team has criteria for interpreting it.', 'Without criteria, every ad becomes another disconnected experiment.'] }, { heading: 'A more sustainable sequence', paragraphs: ['Clarify positioning and offer, build essential touchpoints, establish measurement and then expand distribution. This reduces rework and improves learning quality.', 'Studio Cora connects branding, landing pages and digital presence to keep promise and experience aligned.'] }],
    relatedServices: ['branding', 'landing-pages'], relatedArticles: ['branding-vs-visual-identity'],
  },
]

const articles: Record<Locale, Article[]> = { pt: ptArticles, en: enArticles }

export function getArticles(locale: Locale) { return articles[locale] }
export function getArticle(locale: Locale, slug: string) { return articles[locale].find((article) => article.slug === slug) }
