import type { Locale } from './index'

export type ServicePageData = {
  slug: string
  alternateSlug: string
  title: string
  eyebrow: string
  description: string
  intro: string
  problems: string[]
  included: string[]
  process: { title: string; body: string }[]
  differentiators: string[]
  faq: { question: string; answer: string }[]
  related: string[]
  relatedArticles: string[]
  seoTitle: string
  seoDescription: string
}

const ptServices: ServicePageData[] = [
  {
    slug: 'gestao-de-redes-sociais', alternateSlug: 'social-media-management', title: 'Gestão de Redes Sociais', eyebrow: 'Estratégia, conteúdo e direção criativa',
    description: 'Gestão de redes sociais para empresas que precisam transformar posicionamento, repertório e rotina comercial em uma presença digital clara e consistente.',
    intro: 'A gestão de redes sociais organiza o que a empresa comunica, para quem, com qual linguagem e em quais formatos. Na Studio Cora, estratégia, direção criativa e produção trabalham juntas para que Instagram e outros canais expressem a marca — em vez de apenas preencherem um calendário.',
    problems: ['Empresas estabelecidas cuja presença digital não acompanha a qualidade do negócio', 'Equipes que têm conhecimento, mas não conseguem transformá-lo em pautas e conteúdo recorrente', 'Marcas com comunicação irregular, visual fragmentado ou dependência de ideias de última hora', 'Operações que precisam de direção profissional sem montar uma equipe criativa completa internamente'],
    included: ['Diagnóstico de marca, público, canais e rotina atual', 'Estratégia editorial, pilares de conteúdo e direcionamento de formatos', 'Planejamento de pautas conectado a objetivos e momentos do negócio', 'Direção criativa, design e produção dos conteúdos definidos no escopo', 'Fluxo de briefing, aprovação, organização e acompanhamento editorial'],
    process: [{ title: 'Diagnóstico', body: 'Entendemos o negócio, a marca, o público, a oferta e o papel de cada canal antes de propor pautas.' }, { title: 'Estratégia editorial', body: 'Definimos pilares, temas, linguagem, formatos e critérios para que a produção tenha direção.' }, { title: 'Planejamento e produção', body: 'Organizamos o calendário e desenvolvemos conteúdo dentro de um fluxo claro de colaboração e aprovação.' }, { title: 'Acompanhamento', body: 'Revisamos a resposta do conteúdo e os aprendizados da operação para evoluir pautas e formatos sem perder coerência.' }],
    differentiators: ['Branding, design e conteúdo pensados como um único sistema', 'Estratégia adaptada ao momento e à capacidade operacional da empresa', 'Direção criativa autoral sem transformar a marca em um template', 'Processo próximo entre quem pensa a estratégia e quem executa o conteúdo'],
    faq: [{ question: 'O que uma empresa recebe na gestão de redes sociais?', answer: 'O escopo pode incluir diagnóstico, estratégia editorial, planejamento, direção criativa, design, produção e acompanhamento. A combinação é definida de acordo com os canais, a rotina e a estrutura da empresa.' }, { question: 'A gestão inclui Instagram?', answer: 'Sim. A gestão de Instagram para empresas pode fazer parte do trabalho, junto de outros canais que tenham função real na estratégia.' }, { question: 'Vocês trabalham com um pacote fixo de posts?', answer: 'Não partimos de um volume genérico. A cadência e os formatos são definidos a partir dos objetivos, do repertório disponível e da capacidade de aprovação.' }, { question: 'A Studio Cora também faz branding?', answer: 'Sim. Quando posicionamento e identidade ainda não estão claros, o projeto pode começar ou se conectar a um trabalho de branding.' }],
    related: ['branding', 'identidade-visual'], relatedArticles: ['o-que-e-gestao-de-redes-sociais', 'quanto-custa-gestao-de-redes-sociais', 'como-saber-se-empresa-precisa-social-media'], seoTitle: 'Gestão de Redes Sociais para Empresas', seoDescription: 'Gestão de redes sociais para empresas com estratégia, direção criativa, planejamento e produção de conteúdo consistente.'
  },
  {
    slug: 'branding', alternateSlug: 'branding', title: 'Branding', eyebrow: 'Estratégia e construção de marca',
    description: 'Branding para empresas que precisam definir posicionamento, organizar sua narrativa e construir uma presença reconhecível.',
    intro: 'Branding é o trabalho de organizar como uma empresa quer ser compreendida e como sustenta essa percepção em cada contato. Vai além do logotipo: conecta estratégia de marca, posicionamento, mensagens, identidade e experiência para orientar decisões consistentes.',
    problems: ['Empresas que cresceram, mas continuam se apresentando como no início', 'Marcas parecidas com concorrentes ou difíceis de explicar', 'Times que tomam decisões de comunicação sem critérios compartilhados', 'Negócios preparando uma nova fase, oferta, mercado ou reposicionamento'],
    included: ['Imersão, diagnóstico e leitura do contexto competitivo', 'Posicionamento, proposta de valor e princípios de marca', 'Narrativa, mensagens prioritárias e direção verbal', 'Direção visual e conexão com a identidade visual', 'Orientações para ativação nos principais pontos de contato'],
    process: [{ title: 'Diagnóstico', body: 'Mapeamos contexto, percepção e objetivos.' }, { title: 'Estratégia', body: 'Organizamos posicionamento, atributos e narrativa.' }, { title: 'Direção', body: 'Traduzimos a estratégia em princípios verbais e visuais.' }, { title: 'Ativação', body: 'Preparamos a marca para uso consistente nos pontos de contato.' }],
    differentiators: ['Estratégia conectada à execução', 'Decisões explicáveis e aplicáveis', 'Integração entre marca e experiência digital'],
    faq: [{ question: 'Qual é a diferença entre branding e identidade visual?', answer: 'Branding organiza posicionamento, percepção, narrativa e critérios de decisão. A identidade visual traduz parte dessa estratégia em um sistema de elementos visuais. Um projeto pode incluir as duas frentes, mas elas não são sinônimos.' }, { question: 'Branding é indicado apenas para empresas novas?', answer: 'Não. Empresas maduras também procuram branding quando a marca ficou desalinhada com o negócio, perdeu diferenciação ou precisa preparar uma nova fase.' }, { question: 'A identidade visual pode fazer parte do projeto?', answer: 'Sim. O escopo pode incluir a criação ou evolução do sistema visual após a definição estratégica.' }, { question: 'O projeto entrega um manual de marca?', answer: 'As orientações e os materiais de aplicação são definidos conforme o escopo. O objetivo é deixar critérios úteis para quem continuará operando a marca.' }],
    related: ['identidade-visual', 'desenvolvimento-web'], relatedArticles: ['branding-e-identidade-visual-diferenca', 'quando-empresa-precisa-rebranding', 'branding-antes-de-trafego-pago'], seoTitle: 'Branding e Estratégia de Marca para Empresas', seoDescription: 'Branding para empresas: posicionamento, estratégia de marca, narrativa e direção visual conectados à execução.'
  },
  {
    slug: 'identidade-visual', alternateSlug: 'visual-identity', title: 'Identidade Visual', eyebrow: 'Sistemas visuais para marcas consistentes',
    description: 'Criação de identidade visual para empresas que precisam de uma linguagem própria, consistente e aplicável em diferentes canais.',
    intro: 'Identidade visual é o sistema que torna a marca reconhecível: logotipo quando necessário, tipografia, cores, composição, elementos gráficos e regras de uso. Criamos esse conjunto para funcionar no cotidiano da empresa, não apenas em uma apresentação.',
    problems: ['Visual inconsistente entre canais', 'Identidade que não representa mais o negócio', 'Dependência de soluções improvisadas'],
    included: ['Direção visual', 'Logotipo e assinaturas quando aplicável', 'Paleta, tipografia e elementos gráficos', 'Guia de aplicação'],
    process: [{ title: 'Contexto', body: 'Alinhamos estratégia, necessidades e ambientes de uso.' }, { title: 'Conceito', body: 'Exploramos territórios visuais coerentes com a marca.' }, { title: 'Sistema', body: 'Desenvolvemos elementos e relações de aplicação.' }, { title: 'Entrega', body: 'Organizamos arquivos e orientações para o uso cotidiano.' }],
    differentiators: ['Sistema pensado para uso real', 'Expressão autoral sem perder clareza', 'Continuidade entre identidade e interfaces'],
    faq: [{ question: 'Identidade visual é apenas um logotipo?', answer: 'Não. O logotipo é um dos elementos possíveis. Uma identidade consistente também define tipografia, cores, composição, recursos gráficos e relações de aplicação.' }, { question: 'É possível evoluir uma identidade existente?', answer: 'Sim. Avaliamos o que possui reconhecimento e deve ser preservado antes de redefinir o que perdeu função ou consistência.' }, { question: 'Preciso fazer branding antes?', answer: 'A identidade precisa de uma base estratégica mínima. Quando posicionamento e mensagens ainda estão indefinidos, recomendamos conectar o projeto a uma etapa de branding.' }, { question: 'Quais arquivos são entregues?', answer: 'Os formatos e aplicações dependem do escopo, mas a entrega é organizada para os usos acordados e acompanhada de orientações práticas.' }],
    related: ['branding', 'landing-pages'], relatedArticles: ['branding-e-identidade-visual-diferenca', 'quando-empresa-precisa-rebranding'], seoTitle: 'Criação de Identidade Visual para Empresas', seoDescription: 'Criação de identidade visual e sistemas de marca consistentes, flexíveis e preparados para uso real.'
  },
  {
    slug: 'landing-pages', alternateSlug: 'landing-pages', title: 'Landing Pages', eyebrow: 'Páginas focadas em mensagem e conversão',
    description: 'Criação de landing pages para empresas que precisam apresentar uma oferta com clareza e conduzir visitantes a uma ação específica.',
    intro: 'Uma landing page concentra a atenção em uma oferta, campanha ou lançamento. Estruturamos argumento, conteúdo, interface e desenvolvimento para reduzir distrações, responder objeções e facilitar a próxima ação — sem prometer conversão independente da oferta e do tráfego.',
    problems: ['Campanhas que chegam a páginas genéricas', 'Oferta difícil de compreender rapidamente', 'Experiência lenta ou inconsistente no mobile'],
    included: ['Arquitetura de informação', 'Direção de conteúdo e interface', 'Design responsivo', 'Desenvolvimento e SEO técnico básico'],
    process: [{ title: 'Objetivo', body: 'Definimos oferta, público e ação principal.' }, { title: 'Estrutura', body: 'Organizamos argumento, hierarquia e fluxo.' }, { title: 'Design', body: 'Criamos a interface alinhada à marca.' }, { title: 'Implementação', body: 'Desenvolvemos, testamos e preparamos a publicação.' }],
    differentiators: ['Design e desenvolvimento no mesmo processo', 'Conteúdo rastreável e sem dependência de efeitos', 'Atenção a performance, acessibilidade e mobile'],
    faq: [{ question: 'Landing page é diferente de site institucional?', answer: 'Sim. A landing page costuma trabalhar uma oferta e uma ação principal. O site institucional organiza uma presença mais ampla, com diferentes páginas, públicos e jornadas.' }, { question: 'A página pode ser usada em Google Ads?', answer: 'Sim. A mensagem e a estrutura podem ser alinhadas à intenção da campanha, preservando velocidade, rastreabilidade e clareza.' }, { question: 'Vocês fazem design e desenvolvimento?', answer: 'Sim. Arquitetura de informação, interface e desenvolvimento podem fazer parte do mesmo projeto.' }, { question: 'Vocês garantem uma taxa de conversão?', answer: 'Não. Conversão depende também de oferta, tráfego, preço, reputação e operação comercial. Nosso trabalho é construir uma experiência clara, rápida e tecnicamente sólida.' }],
    related: ['desenvolvimento-web', 'branding'], relatedArticles: ['landing-page-ou-site-institucional', 'quanto-custa-criar-site-profissional'], seoTitle: 'Criação e Desenvolvimento de Landing Pages', seoDescription: 'Criação de landing pages responsivas, rápidas e alinhadas à oferta para campanhas, lançamentos e captação de leads.'
  },
  {
    slug: 'desenvolvimento-web', alternateSlug: 'web-development', title: 'Desenvolvimento Web', eyebrow: 'Experiências digitais com design e engenharia',
    description: 'Desenvolvimento de sites profissionais para empresas que precisam unir posicionamento, conteúdo, experiência e uma base técnica sustentável.',
    intro: 'Um site institucional precisa explicar a empresa, apoiar a decisão comercial e funcionar bem para pessoas e mecanismos de busca. Unimos design e desenvolvimento web para criar experiências responsivas, acessíveis, performáticas e preparadas para evoluir.',
    problems: ['Site lento ou difícil de manter', 'Experiência inconsistente entre dispositivos', 'Tecnologia desconectada do design e do conteúdo'],
    included: ['Arquitetura técnica', 'Implementação responsiva', 'SEO técnico e acessibilidade', 'Integrações definidas no escopo'],
    process: [{ title: 'Descoberta', body: 'Mapeamos requisitos, conteúdo e restrições.' }, { title: 'Arquitetura', body: 'Definimos estrutura, componentes e abordagem técnica.' }, { title: 'Desenvolvimento', body: 'Implementamos em ciclos verificáveis.' }, { title: 'Qualidade', body: 'Validamos comportamento, performance e publicação.' }],
    differentiators: ['Design e engenharia desde o início', 'Código orientado à manutenção', 'Performance tratada como parte da experiência'],
    faq: [{ question: 'Qual tecnologia vocês utilizam?', answer: 'A escolha depende do projeto. Para experiências modernas, trabalhamos com tecnologias como React e Next.js quando elas atendem aos requisitos de conteúdo, performance e manutenção.' }, { question: 'O desenvolvimento inclui SEO?', answer: 'Inclui a base técnica definida no escopo, como estrutura semântica, metadata, indexação e desempenho. Estratégia contínua de conteúdo e autoridade é uma frente complementar.' }, { question: 'Vocês desenvolvem a partir de um design existente?', answer: 'Sim, após avaliar responsividade, estados, conteúdo, acessibilidade e requisitos técnicos.' }, { question: 'Qual é a diferença entre site e landing page?', answer: 'O site organiza a presença institucional e múltiplas jornadas. A landing page concentra uma oferta e uma ação. A escolha depende do objetivo, não apenas do tamanho.' }],
    related: ['landing-pages', 'identidade-visual'], relatedArticles: ['landing-page-ou-site-institucional', 'quanto-custa-criar-site-profissional'], seoTitle: 'Desenvolvimento de Sites para Empresas', seoDescription: 'Desenvolvimento web e criação de sites institucionais responsivos, performáticos e preparados para SEO.'
  },
]

const articleAlternates: Record<string, string> = {
  'o-que-e-gestao-de-redes-sociais': 'what-is-social-media-management',
  'quanto-custa-gestao-de-redes-sociais': 'social-media-management-cost',
  'branding-e-identidade-visual-diferenca': 'branding-vs-visual-identity',
  'quando-empresa-precisa-rebranding': 'when-does-a-company-need-rebranding',
  'landing-page-ou-site-institucional': 'landing-page-vs-corporate-website',
  'quanto-custa-criar-site-profissional': 'professional-website-cost',
  'como-saber-se-empresa-precisa-social-media': 'does-your-company-need-social-media-management',
  'branding-antes-de-trafego-pago': 'branding-before-paid-media',
}

const enServices: ServicePageData[] = ptServices.map((service) => {
  const translations: Record<string, Partial<ServicePageData>> = {
    'gestao-de-redes-sociais': { title: 'Social Media Management', eyebrow: 'Strategy, content and creative direction', description: 'Social media management for companies that need to turn positioning and expertise into a clear, consistent digital presence.', intro: 'Social media management defines what a company communicates, who it needs to reach and how ideas become a sustainable editorial operation. Studio Cora brings strategy, creative direction and production together so each channel expresses the brand instead of merely filling a calendar.', problems: ['Established companies whose social presence no longer reflects the business', 'Teams with valuable expertise but no consistent content operation', 'Fragmented communication across formats and channels', 'Companies that need senior creative direction without building a full internal team'], included: ['Brand, audience and channel diagnosis', 'Editorial strategy, content pillars and format direction', 'Content planning connected to business priorities', 'Creative direction, design and scoped production', 'A clear briefing, review and approval workflow'], process: [{ title: 'Diagnosis', body: 'We learn about the business, audience, offer, brand and the role of each channel.' }, { title: 'Editorial direction', body: 'We define pillars, themes, voice, formats and visual criteria.' }, { title: 'Planning and production', body: 'We build the calendar and create content through a clear collaborative workflow.' }, { title: 'Ongoing refinement', body: 'We review operational learnings and content response to evolve the direction without losing consistency.' }], differentiators: ['Branding, design and content treated as one system', 'A strategy adapted to the company’s actual operation', 'Distinctive creative direction without templating the brand', 'Close collaboration between strategy and production'], faq: [{ question: 'What does a company receive?', answer: 'Scope may include diagnosis, editorial strategy, planning, creative direction, design, production and ongoing guidance. The combination follows the company’s channels and structure.' }, { question: 'Does the service include Instagram management?', answer: 'Yes. Instagram can be part of the work alongside any other channel with a clear role in the strategy.' }, { question: 'Do you sell fixed post packages?', answer: 'We do not begin with a generic volume. Cadence and formats follow goals, available expertise and review capacity.' }, { question: 'Can branding be part of the engagement?', answer: 'Yes. If positioning or identity is unclear, social media work can connect to a branding project.' }], seoTitle: 'Social Media Management for Companies', seoDescription: 'Strategic social media management with editorial direction, planning, design and content production for companies.' },
    branding: { title: 'Branding', eyebrow: 'Brand strategy and positioning', description: 'Branding for companies that need a sharper position, a coherent narrative and a recognizable presence.', intro: 'Branding defines how a company wants to be understood and how it sustains that perception. It reaches beyond a logo, connecting positioning, messaging, identity and experience so teams can make consistent decisions.', problems: ['A growing company still presenting itself like an early-stage business', 'A brand that feels interchangeable with competitors', 'Teams making communication decisions without shared criteria', 'A new phase, market or offer that requires repositioning'], included: ['Immersion, diagnosis and market context', 'Positioning, value proposition and brand principles', 'Narrative, priority messages and verbal direction', 'Visual direction connected to the visual identity', 'Guidance for key brand touchpoints'], process: [{ title: 'Diagnosis', body: 'We map context, perception and business goals.' }, { title: 'Strategy', body: 'We organize positioning, attributes, value and narrative.' }, { title: 'Direction', body: 'We translate strategy into useful verbal and visual principles.' }, { title: 'Activation', body: 'We prepare the brand for consistent use across priority touchpoints.' }], differentiators: ['Strategy connected to execution', 'Decisions designed to be understood and applied', 'Continuity between brand and digital experience'], faq: [{ question: 'Is branding the same as visual identity?', answer: 'No. Branding organizes positioning, perception, narrative and decision criteria. Visual identity turns part of that strategy into a visual system.' }, { question: 'Is branding only for new companies?', answer: 'No. Established companies often need branding when the business has outgrown its positioning or presentation.' }, { question: 'Can visual identity be part of the project?', answer: 'Yes. The scope may include creating or evolving the visual system after the strategic direction is clear.' }, { question: 'Will we receive brand guidelines?', answer: 'Guidance and application materials are defined by scope, with an emphasis on useful criteria for the team operating the brand.' }], seoTitle: 'Branding and Brand Strategy for Companies', seoDescription: 'Brand strategy, positioning, narrative and visual direction for companies building a clear, recognizable brand.' },
    'identidade-visual': { title: 'Visual Identity', eyebrow: 'Visual systems for consistent brands', description: 'Visual identity design for companies that need a distinctive, consistent system across real brand touchpoints.', intro: 'Visual identity is the system that makes a brand recognizable: logo when needed, typography, color, composition, graphic elements and usage rules. We design it for everyday application, not only for a presentation.', problems: ['An inconsistent look across channels', 'An identity that no longer represents the business', 'Dependence on improvised visual solutions'], included: ['Visual direction', 'Logo and signatures when applicable', 'Color, typography and graphic elements', 'Application guidelines'], process: [{ title: 'Context', body: 'We align strategy, needs and real usage environments.' }, { title: 'Concept', body: 'We explore visual territories consistent with the brand.' }, { title: 'System', body: 'We develop elements and application relationships.' }, { title: 'Delivery', body: 'We organize files and practical guidance for daily use.' }], differentiators: ['A system designed for real use', 'Distinctive expression without losing clarity', 'Continuity between identity and interfaces'], faq: [{ question: 'Is visual identity only a logo?', answer: 'No. A useful identity also defines typography, color, composition, graphic elements and relationships between them.' }, { question: 'Can you evolve an existing identity?', answer: 'Yes. We assess what already carries recognition before changing what has lost clarity or function.' }, { question: 'Do we need branding first?', answer: 'Visual decisions need a strategic foundation. If positioning is unclear, we recommend connecting the work to a branding phase.' }, { question: 'Which files are delivered?', answer: 'Formats and applications depend on scope, with files organized for the agreed uses and accompanied by practical guidance.' }], seoTitle: 'Visual Identity Design for Companies', seoDescription: 'Strategic visual identity design and flexible brand systems built for consistent real-world application.' },
    'landing-pages': { title: 'Landing Pages', eyebrow: 'Pages shaped around message and conversion', description: 'Landing page design and development for companies promoting a focused offer, campaign or launch.', intro: 'A landing page concentrates attention on one offer and one primary action. We connect argument, content, interface and development to reduce friction and answer objections—without claiming that a page alone can guarantee conversion.', problems: ['Campaigns leading to generic pages', 'An offer that is hard to understand quickly', 'A slow or inconsistent mobile experience'], included: ['Information architecture', 'Content and interface direction', 'Responsive design', 'Development and foundational technical SEO'], process: [{ title: 'Goal', body: 'We define the offer, audience and primary action.' }, { title: 'Structure', body: 'We organize the argument, hierarchy and journey.' }, { title: 'Design', body: 'We create an interface aligned with the brand.' }, { title: 'Implementation', body: 'We build, test and prepare the page for launch.' }], differentiators: ['Design and development in one process', 'Crawlable content that does not depend on effects', 'Attention to performance, accessibility and mobile'], faq: [{ question: 'How is a landing page different from a corporate website?', answer: 'A landing page supports one offer and action. A corporate website serves broader information needs and multiple journeys.' }, { question: 'Can the page support Google Ads?', answer: 'Yes. Structure and messaging can align with campaign intent while preserving speed and crawlability.' }, { question: 'Do you handle design and development?', answer: 'Yes. Information architecture, interface and development may be included in one project.' }, { question: 'Do you guarantee a conversion rate?', answer: 'No. Conversion also depends on offer, traffic, pricing, reputation and sales operations. We build a clear, fast and technically sound experience.' }], seoTitle: 'Landing Page Design and Development', seoDescription: 'Strategic landing page design and development for campaigns, launches and focused lead-generation offers.' },
    'desenvolvimento-web': { title: 'Web Development', eyebrow: 'Digital experiences built with design and engineering', description: 'Professional web development for companies that need a clear, high-performing and maintainable corporate website.', intro: 'A corporate website must explain the company, support commercial decisions and work well for people and search engines. We bring design and web development together to build responsive, accessible experiences designed to evolve.', problems: ['A slow or difficult-to-maintain website', 'An inconsistent experience across devices', 'Technology disconnected from design and content'], included: ['Technical architecture', 'Responsive implementation', 'Technical SEO and accessibility', 'Scope-specific integrations'], process: [{ title: 'Discovery', body: 'We map requirements, content and constraints.' }, { title: 'Architecture', body: 'We define structure, components and the technical approach.' }, { title: 'Development', body: 'We implement the experience in verifiable cycles.' }, { title: 'Quality', body: 'We validate behavior, performance and release readiness.' }], differentiators: ['Design and engineering involved from the start', 'Code shaped for maintainability', 'Performance treated as part of the experience'], faq: [{ question: 'What technology do you use?', answer: 'Technology follows the project. We use tools such as React and Next.js when they fit content, performance and maintenance needs.' }, { question: 'Does development include SEO?', answer: 'It includes the technical foundation defined in scope, such as semantic structure, metadata, indexability and performance. Ongoing content and authority work are complementary.' }, { question: 'Can you develop from an existing design?', answer: 'Yes, after reviewing responsive behavior, states, content, accessibility and technical requirements.' }, { question: 'What is the difference between a website and a landing page?', answer: 'A website supports institutional presence and multiple journeys. A landing page concentrates on one offer and action.' }], seoTitle: 'Professional Web Development for Companies', seoDescription: 'Responsive web development and corporate websites built around brand, content, performance and technical SEO.' },
  }
  const t = translations[service.slug]
  return { ...service, ...t, slug: service.alternateSlug, alternateSlug: service.slug, related: service.related.map((slug) => ptServices.find((item) => item.slug === slug)?.alternateSlug ?? slug), relatedArticles: service.relatedArticles.map((slug) => articleAlternates[slug] ?? slug) }
})

export function getServices(locale: Locale) { return locale === 'pt' ? ptServices : enServices }
export function getService(locale: Locale, slug: string) { return getServices(locale).find((service) => service.slug === slug) }

export const institutional = {
  pt: {
    about: { eyebrow: 'Sobre o estúdio', title: 'Design e tecnologia trabalhando na mesma direção.', description: 'A Studio Cora constrói presença digital para empresas por meio de estratégia, identidade, conteúdo e experiências digitais.', sections: [{ title: 'Uma visão integrada', body: 'Marca, comunicação e produto digital não vivem separados. Trabalhamos essas frentes como partes de uma mesma experiência.' }, { title: 'Clareza antes do excesso', body: 'Cada decisão precisa ajudar a empresa a ser compreendida, reconhecida e lembrada.' }, { title: 'Da direção à execução', body: 'Estratégia, design e desenvolvimento avançam juntos para reduzir ruído entre ideia e entrega.' }] },
    work: { eyebrow: 'Portfolio', title: 'Trabalho construído com contexto, intenção e cuidado.', description: 'Estamos organizando a documentação pública dos projetos da Studio Cora. Nenhum case será publicado sem contexto e autorização.' },
    insights: { eyebrow: 'Blog', title: 'Ideias sobre marca, conteúdo e experiências digitais.', description: 'Guias práticos para empresas tomarem decisões mais claras sobre branding, redes sociais, landing pages e desenvolvimento web.' },
    contact: { eyebrow: 'Contato', title: 'Vamos conversar sobre o próximo movimento da sua marca.', description: 'Conte brevemente sobre sua empresa, o desafio e o que precisa construir.' },
  },
  en: {
    about: { eyebrow: 'About the studio', title: 'Design and technology moving in the same direction.', description: 'Studio Cora builds digital presence through strategy, identity, content and digital experiences.', sections: [{ title: 'An integrated perspective', body: 'Brand, communication and digital products are parts of the same experience, not isolated disciplines.' }, { title: 'Clarity before excess', body: 'Every decision should help a company be understood, recognized and remembered.' }, { title: 'From direction to execution', body: 'Strategy, design and development move together to reduce the distance between idea and delivery.' }] },
    work: { eyebrow: 'Work', title: 'Work built with context, intention and care.', description: 'We are preparing the public documentation of Studio Cora projects. No case study will be published without context and permission.' },
    insights: { eyebrow: 'Insights', title: 'Ideas on brands, content and digital experiences.', description: 'Practical guidance for companies making decisions about branding, social media, landing pages and web development.' },
    contact: { eyebrow: 'Contact', title: 'Let’s talk about your brand’s next move.', description: 'Tell us briefly about your company, the challenge and what you need to build.' },
  },
} as const
